### ISSUE TITLE
Linux DiscordRP

### ISSUE THREAD

**Issue by BreakingTV** [copyandexecute/noriskclient-issues#1]
DiscordRP funktioniert nicht wenn du auf Linux mit einer Snap installation bist!

**Comment by F0Xde** [comment]
Crash log missing, reopen with added log

**Comment by byquanton** [comment]
just install discord via apt with their debian file

**Comment by xaiyadev** [comment]
If I make that I can't use BetterDiscord

**Comment by xaiyadev** [comment]
I got it my self now thx for help!
