### ISSUE TITLE
Mac Crash Issue

### ISSUE THREAD

**Issue by Walentinik** [copyandexecute/noriskclient-issues#12]
[Mac Crash Nachricht.txt](https://github.com/copyandexecute/noriskclient-issues/files/5705014/Mac.Crash.Nachricht.txt)

**Comment by Paulaufyt** [comment]
[crash-2020-12-16_20.20.32-client.txt](https://github.com/copyandexecute/noriskclient-issues/files/5705047/crash-2020-12-16_20.20.32-client.txt)
ich hab das selbe problem

**Comment by Woody1474747** [comment]
Glaube liegt an der Discord Rich presence

**Comment by FlynnLG** [comment]
Gleiche Problem. Und ja es liegt an Discord Rich Presence, habe nur keine Ahnung, wie man es behebt.
