### ISSUE TITLE
Forge Crasht

### ISSUE THREAD

**Issue by Ashori1** [copyandexecute/noriskclient-issues#15]
Hallo! Wenn ich mit dem Client in meinem Modfolder versuche, das Spiel zu starten, crasht es. |  https://prnt.sc/w46dvd  | (Das ist ein Screenshot)

Details:
Ich hab fast alles versucht. Damit meine ich: -Forge neu installiert. (Die Version aus dem Discord und auch andere)
                                                                       -Den Client mehrmals neu heruntergeladen.
                                                                       -Ich hatte Forge für 1.7.10 und auch für die 1.8.9, und hatte demensprechend 
                                                                        seperate Folder im Modfolder für die jeweiligen Versionen. Habe auch hier, die 
                                                                        1.7.10 Version gelöscht, und dann nur ein Forge gehabt (für 1.8.9), ohne seperaten 
                                                                        1.8.9 Folder.
                                                                       -Alle anderen Mods außer den Client gelöscht, auch Optifine. (habs natürlich vorher 
                                                                        mit Optifine versucht)

Wäre schön wenn mir jmd weiterhelfen könnte.

Danke im Vorraus

**Comment by F0Xde** [comment]
Bitte relevante Teile des Crash-Logs anfügen
