### ISSUE TITLE
Fehlercode: -1

### ISSUE THREAD

**Issue by StrangeJoni** [copyandexecute/noriskclient-issues#21]
The game crashed whilst initializing game
Error: java.lang.VerifyError: Bad type on operand stack
Exit Code: -1

**Comment by F0Xde** [comment]
Bitte relevante Teile des Crash-Logs anfügen

**Comment by StrangeJoni** [comment]
[crash-2020-12-17_01.50.03-client.txt](https://github.com/copyandexecute/noriskclient-issues/files/5707626/crash-2020-12-17_01.50.03-client.txt)

das ist die Datei dazu
