### ISSUE TITLE
Spiel crasht beim betreten einer Single-Player Welt

### ISSUE THREAD

**Issue by DasIschBims** [copyandexecute/noriskclient-issues#22]
Ich haue am besten mal den Crash-Log hier rein.
[crash-2020-12-16_20.36.39-server.txt](https://github.com/copyandexecute/noriskclient-issues/files/5705120/crash-2020-12-16_20.36.39-server.txt)
Falls das irgendwie weiterhilft ;)

LG- DasIschBims

**Comment by F0Xde** [comment]
Sieht nicht nach einem NoRiskClient bedingten Fehler aus, kannst du die Welt mit Vanilla bzw Forge ohne den Client betreten?

**Comment by Bims-sh** [comment]
Also ich habe die Welt erst neu generiert, in Vanilla Minecraft klappt sie ohne Probleme.
