### ISSUE TITLE
MouseHotkey 

### ISSUE THREAD

**Issue by SenpaiUnknnown** [copyandexecute/noriskclient-issues#23]
sobald ich meine seitlich Maustaste drücke/Mittlere und versuche ein Item auf den Platz hin oder wegzuziehen ... passiert nichts 

Der krasse Senpai wartet auf Hilfe 
Norisk antwortet mir nicht nach 3 markierten antworten xD 
trotzdem geiler Client !

**Comment by F0Xde** [comment]
Duplicate of #20 (?)

**Comment by copyandexecute** [comment]
Should be fixxed with version > 0.0.1
